services:
  portainer:
    image: portainer/portainer-ce:latest
    pull_policy: always
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=portainer.unklab.id
      - VIRTUAL_PORT=443

volumes:
  portainer_data:
